### ISSUE TITLE
Single pages for DML, DDL, DCL

### ISSUE THREAD

**Issue by BenediktStuhrmann** [hoschmi/WebGoat#2]
Bei den SQL-Injections DML, DDL und DCL jeweils kurz auf einer eigenen Seite erklären und jeweils eine kleine SQL-Aufgabe (keine Injections) hinzufügen, welche sich auf die jeweilige Sprache bezieht.

1. **DML**: z.B. Nutzer soll bestimmte Daten auslesen/ändern (SELECT, UPDATE ...)
2. **DDL**: z.B. Nutzer soll Table löschen/ändern (DROP, ALTER...)
3. **DCL**: z.B. Nutzer soll Zugriffsrechte ändern (GRANT, REVOKE ...)

(Seiten bereits im Zuge von #4 erstellt )

<hr>
**Time:**
Planned: 1h
Needed: 1h

**Comment by Timurlin** [comment]
Ich mach's.

**Comment by PhilippeSteinbach** [comment]
Übernehme hier...
