### ISSUE TITLE
Nothing happens when submitting quiz

### ISSUE THREAD

**Issue by BenediktStuhrmann** [hoschmi/WebGoat#23]
Nothing happens when submitting quiz SQL-advanced quiz.

Feedback needed for the user.

**Comment by MaxGeldner** [comment]
Hallo.
dupliziert #16

**Comment by BenediktStuhrmann** [comment]
Achso okay. Dachte #16 bezieht sich nur auf die andere Aufgabe

**Comment by MaxGeldner** [comment]
Hab übrigens immer noch keine Ahnung warum das nicht geht. Der Code deckt sich mit dem bei den Aufgaben, wo es funktioniert.
