### ISSUE TITLE
SQL-Injection: Queries in SQL-Injection introduction bugs

### ISSUE THREAD

**Issue by Timurlin** [hoschmi/WebGoat#49]

**Comment by Aywaa** [comment]
Seite 2: Kann auch gelöst werden, indem man den Nutzer "John Smith" sucht, da er das gleiche Department hat wie Bob Franco. Kann ich gleich schnell fixen

**Comment by Aywaa** [comment]
Seite 9 & 10: Aufgaben werden nicht grün bei bestehen

**Comment by Aywaa** [comment]
Page 12: Maybe another last hint that you have to add a "--" to comment out the last bit of the old sql

**Comment by BenediktStuhrmann** [comment]
Page 2: When inputting **SELECT * FROM employees;** response ist _Something went wrong! You got no results, check your SQL Statement and the table above_ instead of something like _This is not the query we're looking for._ (since the sql is syntactically correct)

**Comment by BenediktStuhrmann** [comment]
Page 3: Error: *invalid cursor state: identifier cursor not positioned on row in UPDATE, DELETE, SET, or GET statement: ; ResultSet is positioned before first row* when using correct solution

**Comment by BenediktStuhrmann** [comment]
Page 9: Maybe use SqlInjectionLesson8.generateTable() function to print the table for better readability

**Comment by BenediktStuhrmann** [comment]
> Page 9 & 10: Lessons wont be marked as done if succesfully

@Aywaa Marked green/done for me.

**Comment by BenediktStuhrmann** [comment]
Pages 2,3,4,5: Not marked as completed after success
