### ISSUE TITLE
Password Reset Research

### ISSUE THREAD

**Issue by Timurlin** [hoschmi/WebGoat#58]

**Comment by BenediktStuhrmann** [comment]
Page 3: Images could be larger. Elaborate explanation.

**Comment by BenediktStuhrmann** [comment]
Page 4: Unclear how lesson should be completed. You can either guess or bruteforce it? (most common names and colors)

**Comment by BenediktStuhrmann** [comment]
Page 5: Request needs to be intercepted with an external tool. But no word about it (not even a hint). Maybe improve description and hints?

**Comment by MaxGeldner** [comment]
Ich denke es ist schwer hier eine klassische Mitigation Aufgabe zu erstellen (zum Beispiel mit Code Editor?). Wir können aber die Mitigation Sachen wieder mit unseren Quiz lösen? Fragen könnten folgende Inhalte abfragen:
- Wie sollten Sicherheitsfragen gestellt werden (festgelegte Fragen/Antworten, frei gestellte Fragen mit frei gestellten Antworten, ...)
- Welche Daten sollten nicht über das Netzwerk gesendet werden (z.B. der Nutzername, ...)
- Wie sollte verfahren werden, wenn Sicherheitsfragen falsch beantwortet werden (limitierte Anzahl an Versuchen, zeitliches Sperren des Accounts). Brute Force Beantwortung sollte hier eventuell irgendwie verhindert werden
- Eventuell was zu Multi-Faktor Autorisierung (wann ist das sinnvoll in diesem Kontext?)
- Etwas zur Haltbarkeit von PW-Reset Codes
- Um überhaupt auf die PW-Reset Seite zu kommen sollte alle vorherigen Schritte abgeschlossen werden, wie kann das sichergestellt werden? (sonst kann mit Brute Force einfach ein PW-Reset Link gefunden werden)
- Zum Thema Logging: Was sollte geloggt werden, warum ist das wichtig?

Im Prinzip steht das meiste dazu in dem Cheat Sheet: https://www.owasp.org/index.php/Forgot_Password_Cheat_Sheet

**Comment by MaxGeldner** [comment]
Außerdem findet das oben genannte Cheat Sheet irgendwie keine Erwähnung in der Lesson? Wir könnte eine Seite erstellen, in der die Inhalte kurz zusammengefasst werden oder einfach auf das Cheat Sheet verweisen.

**Comment by MaxGeldner** [comment]
> Page 4: Unclear how lesson should be completed. You can either guess or bruteforce it? (most common names and colors)

Ich glaube, dass das der Sinn davon ist (?). Es geht ja darum klar zu stellen, wie sinnlos solche einfachen Sicherheitsfragen sind und wie einfach es ist sowas zu Brute Forcen.

**Comment by MaxGeldner** [comment]
NIST-Standard erwähnen?
