### ISSUE TITLE
Consider changing the category of XXE

### ISSUE THREAD

**Issue by MaxGeldner** [hoschmi/WebGoat#73]

**Comment by MaxGeldner** [comment]
Würde die Kategorie denke ich doch nicht ändern. Das passt ganz gut zu Injection Flaws. Wenn wir das und SQL Injection noch aufteilen, haben wir zu viele Kategorien mit jeweils zu wenigen Lessons. Ist wahrscheinlich sinnvoll solche Sachen beisammen zu halten.

**Comment by Timurlin** [comment]
Ergebis : XXE bleibt da wo es ist.
