### ISSUE TITLE
Assignment for NIST password standards lesson

### ISSUE THREAD

**Issue by BenediktStuhrmann** [hoschmi/WebGoat#80]
Time planned: 2h
Time needed: 3,5h

**Comment by BenediktStuhrmann** [comment]
Kann das hier gerne noch übernehmen, sofern denn jemand ne Idee hätte, was man als Aufgabe machen könnte. @PhilippeSteinbach @MaxGeldner @Aywaa @Timurlin @Tobias-Melzer

**Comment by PhilippeSteinbach** [comment]
Ich habe folgende Vorschläge:

- User muss ein sicheres Passwort eingeben nach NIST Vorgabe/Empfehlung
- User macht Quiz über Sicherheitsmerkmale von sicheren Passwörtern

**Comment by BenediktStuhrmann** [comment]
> User muss ein sicheres Passwort eingeben nach NIST Vorgabe/Empfehlung

Das wäre dann quasi "gib mindestens 8 Zeichen ein" 😆 

Und Quiz könnte man theoretisch machen. Finde Quiz nur nicht so spannend/interessant wie ne "richtige" Aufgabe 🤔

**Comment by PhilippeSteinbach** [comment]
https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Implement_Proper_Password_Strength_Controls

Würde hier mal was probieren und das User Passwort auf diese Kriterien abfragen.

**Comment by BenediktStuhrmann** [comment]
Hm das widerspricht irgendwie etwas dem NIST Standard 😅 
Da heißt es nämlich eigentlich man soll dem Nutzer zwar alle Möglichkeiten geben, ihm aber quasi keine Anforderungen auferlegen (wie jetzt zB muss ein Sonderzeichen und nen Großbuchstaben enthalten etc.)

**Comment by MaxGeldner** [comment]
^
Ich glaube eine Aufgabe dazu ist eher unnötig. Wir können den Nutzer Passwörter eingeben lassen und daneben hinschreiben, wie lange es im Schnitt brauchen würde das Passwort zu knacken. Da kann man dann darauf hinweisen, dass die Länge des Passwort wichtiger ist als die Größe des verwendeten Zeichensatzes. Ich glaube das ist ja eine der Punkte, die auch in dem Standard angesprochen werden (soweit ich mich an die Vorlesung erinnern kann).

**Comment by BenediktStuhrmann** [comment]
Du meinst quasi die Entropiebits der Eingabe berechnen und dann daraus grob die Zeit kalkulieren?

**Comment by MaxGeldner** [comment]
Ja, fände das irgendwie recht interessant. Könnte der Nutzer etwas mit den "Vorgaben" im Standard rumspielen. Man kann aber leider keine Zeit für einen nicht naiven Brute Force Angriff angeben. Also wie das zum Beispiel damals in IT-Sec erklärt wurde, da Nutzer ihre Zahlen meistens ans Ende hängen, wenn das Passwort eine Zahl benötigt und so weiter. Muss man sich überlegen, wie man das einbaut oder ob das nur erklären will.

**Comment by BenediktStuhrmann** [comment]
Klingt finde ich gut 👍 
@PhilippeSteinbach übernimmst du das? (hast dir das zumindest zugewiesen)
Sonst kann ich das auch gerne machen.

**Comment by PhilippeSteinbach** [comment]
Sitze bereits dran, ja ;)
Unter Verwendung von https://github.com/dropbox/zxcvbn bekomme ich z.B. Folgende Werte, die man zum Passwort zeigen könnte:

pw: Visit_4Madman_film6
len: 19
guesses: 6.1851664E15
score: 4
time to crack: 618516.64
Day 7158757 Hour 9 Minute 46 Seconds 40

pw: admin
len: 5
guesses: 716.0
score: 0
time to crack: 7.16E-8
Day 0 Hour 0 Minute 0 Seconds 0

**Comment by PhilippeSteinbach** [comment]
https://github.com/dropbox/zxcvbn#usage

Was haltet ihr davon @BenediktStuhrmann @MaxGeldner

**Comment by MarvinSchoening** [comment]
sieht ganz gut aus finde ich und da es anscheinend von dropbox ist, siehts auch nach einer "seriösen" quelle aus
